spring:
  datasource:
    url: jdbc:mysql://localhost:3306/douban?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 794613
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
